=== SerenityOS/serenity/Ports/jdk/jdk-jdk-18-10/test/jaxp/javax/xml/jaxp/unittest/transform/Bug4693341.dtd
<!ELEMENT SupplierOrder (OrderId, OrderDate, ShippingAddress, LineItems)>

<!ELEMENT OrderId (#PCDATA)>

<!ELEMENT OrderDate (#PCDATA)>

<!ELEMENT ShippingAddress (FirstName, LastName, Street, City, State, Country, ZipCode, Email, Phone)>

<!ELEMENT FirstName (#PCDATA)>

<!ELEMENT LastName (#PCDATA)>

<!ELEMENT Street (#PCDATA)>

<!ELEMENT City (#PCDATA)>

<!ELEMENT State (#PCDATA)>

<!ELEMENT Country (#PCDATA)>

<!ELEMENT ZipCode (#PCDATA)>

<!ELEMENT Email (#PCDATA)>

<!ELEMENT Phone (#PCDATA)>

<!ELEMENT LineItems (LineItem+)>

<!ELEMENT LineItem EMPTY>

<!ATTLIST LineItem
     categoryId CDATA #REQUIRED
     productId CDATA #REQUIRED
     itemId CDATA #REQUIRED
     lineNo CDATA #REQUIRED
     quantity CDATA #REQUIRED
     unitPrice CDATA #REQUIRED
>

=== SerenityOS/serenity/Ports/jdk/jdk-jdk-18-10/test/jaxp/javax/xml/jaxp/unittest/transform/Bug4693341.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SupplierOrder SYSTEM "Bug4693341.dtd" >
<SupplierOrder>
<OrderId>10016</OrderId>
<OrderDate>Wed May 29 12:45:00 PDT 2002</OrderDate>
<ShippingAddress>
<FirstName>ABC</FirstName>
<LastName>XYZ</LastName>
<Street>1234 Anywhere Street</Street>
<City>Palo Alto</City>
<State>California</State>
<Country>USA</Country>
<ZipCode>94303</ZipCode>
<Email>NULL</Email>
<Phone>NULL</Phone>
</ShippingAddress>
<LineItems>
<LineItem categoryId="BIRDS" itemId="EST-18" lineNo="0" productId="AV-CB-01" quantity="1" unitPrice="193.5"/>
</LineItems>
</SupplierOrder>
