<?xml version="1.0"?>
<!DOCTYPE note [
<!ELEMENT note    (#PCDATA|to|ar:from|br:from|heading|body)*>
<!ELEMENT to      (#PCDATA)>
<!ELEMENT ar:from    (#PCDATA)>
<!ELEMENT br:from    (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body    (#PCDATA)>
<!ATTLIST note xmlns:ar CDATA #IMPLIED>
<!ATTLIST note xmlns:br CDATA #IMPLIED>
]>
<note xmlns:ar="http://www.xml.com/books">
      xmlns:br="http://www.abc.com">
<to>Tove</to>
<ar:from>Jani</ar:from>
<br:from>Next</br:from>
<heading>Reminder</heading>
<body> weekend!</body>
</note> 
